name: sugmps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  image: ^4.1.4
  image_picker: ^1.1.1
  font_awesome_flutter: ^10.4.0
  tflite_flutter: ^0.11.0
  vector_math: ^2.1.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  video_player: ^2.8.2
  shared_preferences: ^2.2.1
  google_mlkit_pose_detection: ^0.11.0  # Downgraded to match available versions
  google_mlkit_commons: ^0.7.1
<<<<<<< HEAD
=======
  
>>>>>>> bf54a62 (Detections implemented fully, errors fixed, folders added for modularity and clarity(utils and detections folder), redirecvtions implemented)
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section - make sure movenet.tflite is included
  assets:
    - assets/wo_image.png
    - assets/wo_image1.png
    - assets/wo_image2.png
    - assets/wo_image3.png
    - assets/wo_image4.png
    - assets/movenet.tflite
    - assets/squat_video.mp4  # Add this line
